sudo: false
language: ruby
cache: bundler
rvm:
- 2.5
- 2.6
- ruby-head
matrix:
  fast_finish: true
  allow_failures:
  - rvm: ruby-head
before_install:
- gem update --system
- gem install bundler
install:
- bundle install --jobs=3 --retry=3
script:
- bundle exec rspec
- bundle exec rubocop
- bundle exec fasterer
notifications:
  email: false
  slack:
    secure: WfhmFTV6f3MEr/yAEiY44A1ih8mO5WZpOO3ltCfPxULEIJZx3IEiXtsycuenyyV/Woz6LE3L1mc/Rka985KrHvsYGXzl+NCfE5SNB+XgrXYdvy4wCcb60lDrILeziCKgTHPu2YHatiJDVL6Z+pawUxEAb7VvK7UnrNbr+YmVr/KgfWFnJ8NKq2mMVLt0Caqg8IKibTP+AcLpankPnfMHgfHkOSMygx/vumbqjDm3siY11b2Kob/1NtGBkH0iZ4F1V+WS36g3FCD3nA43NlFmHivAN1NTaGicjEIS26T03F5bwEEHmw6MpPTVV1ntC2prsNAnlNFyxsLcWEFqovuAXpdrhjhHEw6Ti8gXjq8TKVeFIbmveHCAVa0aAkUnkF71HRePXTUckeog5XWbE2LQfnj9jzwbKnkNbifTxgUsUkF8TQDIrSjROsR2RV+HZ91g3XZi3VlmUqShaWgU5/SugPy2qcho17X2AF3wLOqFyCxPs6kvxwjRyrAJCZHzCirCcrfTlha3Go46KPadRL+gfU54Spzot4HPeMLBa0G5pupmyE5kdJ9ryC9WidNScE1NxtGNAHaDOWE86ONTShJaFCnfmAidLMjx/tepxwWrvuyrQL6cEpt3avLtqgKHqqC8REXpxuNitcLTRaKwql136UDrx28DgL3ycrdP7PqsWDY=
